export const defaultPhrases: string[] = [
	// Cloud & Infrastructure
	'Azure',
	'AWS',
	'Kubernetes',
	'Docker',
	'Terraform',
	'Bicep',
	'ARM template',
	'virtual machine',
	'load balancer',
	'availability zone',
	'scale set',
	'App Service',
	'Azure Functions',
	'serverless',
	'microservices',
	'container instance',
	'AKS',
	'Azure Kubernetes Service',

	// DevOps & CI/CD
	'DevOps',
	'CI/CD',
	'pipeline',
	'GitHub Actions',
	'Azure DevOps',
	'Infrastructure as Code',
	'GitOps',
	'Helm chart',
	'YAML',
	'artifact',
	'deployment slot',

	// Security & Identity
	'Entra ID',
	'Azure AD',
	'Conditional Access',
	'zero trust',
	'RBAC',
	'managed identity',
	'service principal',
	'OAuth',
	'SAML',
	'multi-factor authentication',
	'MFA',
	'Privileged Identity Management',
	'PIM',
	'Microsoft Defender',
	'Sentinel',
	'SIEM',

	// AI & Data
	'Copilot',
	'GPT',
	'large language model',
	'LLM',
	'Azure OpenAI',
	'Cognitive Services',
	'machine learning',
	'Power BI',
	'Fabric',
	'Synapse',
	'Data Factory',
	'RAG',
	'retrieval augmented generation',
	'prompt engineering',

	// Networking
	'virtual network',
	'VNet',
	'subnet',
	'NSG',
	'Azure Firewall',
	'Application Gateway',
	'Front Door',
	'Private Endpoint',
	'ExpressRoute',
	'VPN gateway',
	'DNS',

	// Development & Platform
	'TypeScript',
	'JavaScript',
	'API',
	'REST',
	'GraphQL',
	'SDK',
	'NuGet',
	'npm',
	'Visual Studio',
	'VS Code',

	// Microsoft 365 & Platform
	'Microsoft 365',
	'SharePoint',
	'Teams',
	'Power Platform',
	'Power Automate',
	'Intune',
	'Autopilot',
	'Windows 365',
	'Azure Virtual Desktop',
	'AVD'
];
